name: gslam-jetson
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  
  # PyTorch ecosystem - CUDA 12.2 compatible
  - pytorch=2.1.0
  - torchvision=0.18.0
  - torchaudio=2.1.0
  - pytorch-cuda=12.1
  
  # Core scientific computing
  - numpy=1.24.3
  - scipy=1.10.1
  - opencv=4.8.0
  - pillow=10.0.1
  
  # 3D processing and visualization
  - matplotlib=3.7.2
  - plotly=5.17.0
  - imageio=2.31.1
  - imageio-ffmpeg=0.4.9
  - tqdm=4.66.1
  
  # Data handling
  - pandas=2.0.3
  - pyyaml=6.0.1
  - h5py=3.9.0
  
  # Development tools
  - ipython=8.15.0
  - jupyter=1.0.0
  - git
  
  # CUDA and GPU support
  - cudatoolkit=12.2
  - nvidia-ml-py
  
  # Dependencies for Jetson Orin
  - pip:
    # 3D processing
    - open3d==0.17.0
    - trimesh==3.23.5
    - plyfile==1.0.1
    - 
    # SLAM specific
    - lpips==0.1.4
    - kornia==0.7.0
    - roma==1.4.1
    - diff-gaussian-rasterization
    - simple-knn
    
    # Jetson utilities
    - jetson-stats==4.2.7
    - jtop
    - psutil==5.9.5
    
    # TensorRT for inference optimization (Jetson specific)
    - tensorrt==8.6.1
    - pycuda==2022.2.2
    
    # Image processing
    - scikit-image==0.21.0
    - albumentations==1.3.1
    
    # Logging and monitoring
    - wandb==0.15.12
    - tensorboard==2.14.0
    
    # Additional utilities
    - rich==13.5.2
    - typer==0.9.0
    - natsort==8.4.0
    
    # Memory profiling for optimization
    - memory-profiler==0.61.0
    - pympler==0.9
    
    # Configuration management
    - hydra-core==1.3.2
    - omegaconf==2.3.0
